apiVersion: v1
kind: Service
metadata:
  name: openeew
  labels:
    k8s-app: openeew
spec:
  selector:
    k8s-app: openeew
  type: NodePort
  ports:
   - port: 1883
     nodePort: 31883
     name: mqtt
