name: CI

on:
  # Execute on every push to any branch
  push:
    branches:
      - "**"
  # Execute on every pull request to the master branch
  pull_request_target:
    branches:
      - master

jobs:
  publish:
    name: Build and publish openeew/detector Docker image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.1
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - run: pip install --requirement requirements.txt
      - run: PYTHONPATH=./openeew:./test python -m unittest
