name: CI

on:
  create:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  publish:
    name: Build and publish openeew/detector Docker image
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - uses: actions/checkout@v2.3.1
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - run: pip install -requirement requirements.txt
      - run: PYTHONPATH=./openeew python -m unittest
      - if: success() && github.event_name == 'create'
        uses: docker/build-push-action@v1.1.0
        with:
          repository: openeew/detector
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tags: latest
          tag_with_ref: true
          push: ${{ startsWith(github.ref, 'refs/tags/') }}
          add_git_labels: true
