name: CI

on:
  push:
    branches: [master]

jobs:
  publish:
    name: Build and publish openeew/detector Docker image
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - uses: docker/build-push-action@v1.1.0
        with:
          repository: openeew/detector
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tags: latest
          tag_with_ref: true
          push: ${{ startsWith(github.ref, 'refs/tags/') }}
          add_git_labels: true
